### PR TITLE
Return empty div when result count === -1

### PR DESCRIPTION
**Pull request by m-gagne**
Resolves Issue #9 by checking the result count, if -1 an empty div element is returned.

### CODE REVIEW

**Comment by EvanBoyle** [comment]
Did you check and see if this works if count is set to false in searchParameters? I think if count is false, then the value will always be -1. After reading through the code a better property to check would be state.results.lastUpdated. This value is set to zero until the first query is issued. That would probably also solve the problem with displaying range facets. What do you think?

**Review by EvanBoyle — CHANGES_REQUESTED** [review]
I think this would be buggy if the user sets count: false in searchParameters. I realize that we should be able to check state.results.lastUpdated which is always zero on page load, and gets updated with every request.

**Comment by m-gagne** [comment]
Updated this PR & the Issue #5 to both use lastUpdated which as you pointed out *actually* works =)

**Review by EvanBoyle — APPROVED** [review]

**Comment by EvanBoyle** [comment]
Thanks Marc!

**Pull request merged**
